version: "3"
services:
  api:
    build: .
    container_name: cibic_api
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - "3000:3000"
    depends_on:
      - mongo_serve
    links:
      - mongo_serve
    tty: true
  mongo_serve:
    container_name: cibic_mongodb
    image: mongo
    ports:
      - "27018:27017"
  node_router:
    build: node_router
    container_name: node_router
    volumes:
     - './node_router:/srv'
     - '/srv/node_modules'
    ports:
      - "443:443"
