version: "3.2"
volumes:
  api_modules:
services:
  api:
    build: .
    image: cibic_api
    container_name: cibic_api
    entrypoint: npm run
    environment:
      DEPLOY_ENV: development
    volumes:
      - type: bind
        source: ./app
        target: /app
      - type: volume
        source: api_modules
        target: /app/node_modules
    depends_on:
      - mongo_serve
    links:
      - mongo_serve
    tty: true
    stdin_open: true
  mongo_serve:
    image: mongo
    container_name: cibic_mongodb
    expose:
      - "27017"

